name: 🐛 Bug Report
description: Create a report to help us improve Maestro Energy Management
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Maestro are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Frontend (React App)
        - Backend (API Server)
        - Protocol Adapters
        - Database
        - Docker Setup
        - CI/CD Pipeline
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "The device control fails when..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment:
      value: |
        - OS: [e.g. Windows 10, macOS 12.0, Ubuntu 20.04]
        - Browser: [e.g. Chrome 96, Firefox 95, Safari 15]
        - Node.js Version: [e.g. 18.17.0]
        - Docker Version: [if applicable]
        - Device Type: [e.g. Tuya Smart Plug Model XYZ]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, add logs to help explain your problem.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as screenshots.

  - type: checkboxes
    id: terms
    attributes:
      label: Checks
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all the required information
          required: true
        - label: This issue is related to Maestro Energy Management System
          required: true